apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus
  namespace: argo
spec:
  destination:
    namespace: monitoring
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: x.x.x
    chart: kube-prometheus-stack
    helm:
      version: v3
      valueFiles:
        - https://raw.githubusercontent.com/incubator4/k3s-monitor/main/kube-prometheus/values.yaml
  project: monitor
  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - ApplyOutOfSyncOnly=true
