apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # - victoria-metrics.yaml
  - github.com/VictoriaMetrics/operator/config/default?ref=v0.25.1

images:
  - name: victoriametrics/operator
    newTag: v0.25.1
